 --> The “group by” process: split-apply-combine

(1) Splitting the data into groups. (2). Applying a function to each group independently, (3) Combining the results into a data structure.

Aggregation: compute a summary statistic for each group. for example, sum, mean, or count.

Transformation: perform some group-specific computations and return a like-indexed object. For example, standardize data within a group or replacing missing values within groups.

Filtration: discard some groups, according to a group-wise computation that evaluates True or False. For example, discard data that belongs to groups with only a few members or filter out data based on the group sum or mean.

In [1]:
import pandas as pd
import numpy as np

In [4]:
student_list = [{'name': 'John', 'major': "Computer Science", 'gender': "male"},
                {'name': 'Nate', 'major': "Computer Science", 'gender': "male"},
                {'name': 'Abraham', 'major': "Physics", 'gender': "male"},
                {'name': 'Brian', 'major': "Psychology", 'gender': "male"},
                {'name': 'Janny', 'major': "Economics", 'gender': "female"},
                {'name': 'Yuna', 'major': "Economics", 'gender': "female"},
                {'name': 'Jeniffer', 'major': "Computer Science", 'gender': "female"},
                {'name': 'Edward', 'major': "Computer Science", 'gender': "male"},
                {'name': 'Zara', 'major': "Psychology", 'gender': "female"},
                {'name': 'Wendy', 'major': "Economics", 'gender': "female"},
                {'name': 'Sera', 'major': "Psychology", 'gender': "female"}
         ]
df = pd.DataFrame(student_list, columns = ['name', 'major', 'gender'])
df

        name             major  gender
0       John  Computer Science    male
1       Nate  Computer Science    male
2    Abraham           Physics    male
3      Brian        Psychology    male
4      Janny         Economics  female
5       Yuna         Economics  female
6   Jeniffer  Computer Science  female
7     Edward  Computer Science    male
8       Zara        Psychology  female
9      Wendy         Economics  female
10      Sera        Psychology  female

In [5]:
groupby_major = df.groupby('major')

In [6]:
groupby_major.groups

{'Computer Science': [0, 1, 6, 7], 'Economics': [4, 5, 9], 'Physics': [2], 'Psychology': [3, 8, 10]}

In [4]:
ipl_data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils','Kings',
   'kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
   'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2],
   'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
   'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df = pd.DataFrame(ipl_data)
print(df)

      Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690

In [5]:
#groupby team
print (df.groupby('Team'))

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x0000028FD29E1910>

In [7]:
#to view groups
print (df.groupby('Team').groups)

{'Devils': [2, 3], 'Kings': [4, 6, 7], 'Riders': [0, 1, 8, 11], 'Royals': [9, 10], 'kings': [5]}

In [8]:
print(df.groupby(['Team','Year']).groups)

{('Devils', 2014): [2], ('Devils', 2015): [3], ('Kings', 2014): [4], ('Kings', 2016): [6], ('Kings', 2017): [7], ('Riders', 2014): [0], ('Riders', 2015): [1], ('Riders', 2016): [8], ('Riders', 2017): [11], ('Royals', 2014): [9], ('Royals', 2015): [10], ('kings', 2015): [5]}

In [9]:
grouped = df.groupby('Year')

for name,group in grouped:
    print(name)
    print (group)

2014
     Team  Rank  Year  Points
0  Riders     1  2014     876
2  Devils     2  2014     863
4   Kings     3  2014     741
9  Royals     4  2014     701
2015
      Team  Rank  Year  Points
1   Riders     2  2015     789
3   Devils     3  2015     673
5    kings     4  2015     812
10  Royals     1  2015     804
2016
     Team  Rank  Year  Points
6   Kings     1  2016     756
8  Riders     2  2016     694
2017
      Team  Rank  Year  Points
7    Kings     1  2017     788
11  Riders     2  2017     690

In [11]:
#Select a Group
grouped = df.groupby('Year')
print(grouped.get_group(2016))

     Team  Rank  Year  Points
6   Kings     1  2016     756
8  Riders     2  2016     694

-->Aggregations

An aggregated function returns a single aggregated value for each group. Once the group by object is created, several aggregation operations can be performed on the grouped data by using agg method.

In [14]:
grouped = df.groupby('Year')
print(grouped['Points'].agg(np.mean))

Year
2014    795.25
2015    769.50
2016    725.00
2017    739.00
Name: Points, dtype: float64

Applying Multiple Aggregation Functions at Once

In [15]:
grouped=df.groupby('Team')
print(grouped['Points'].agg([np.sum,np.mean,np.std]))

         sum        mean         std
Team
Devils  1536  768.000000  134.350288
Kings   2285  761.666667   24.006943
Riders  3049  762.250000   88.567771
Royals  1505  752.500000   72.831998
kings    812  812.000000         NaN

In [17]:
print(df.groupby('Team').size())

Team
Devils    2
Kings     3
Riders    4
Royals    2
kings     1
dtype: int64

In [21]:
df_r = df.groupby('Team').get_group('Riders')
df_r

      Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
8   Riders     2  2016     694
11  Riders     2  2017     690

In [23]:
p=df.groupby('Team').mean()
p

            Rank         Year      Points
Team
Devils  2.500000  2014.500000  768.000000
Kings   1.666667  2015.666667  761.666667
Riders  1.750000  2015.500000  762.250000
Royals  2.500000  2014.500000  752.500000
kings   4.000000  2015.000000  812.000000

In [25]:
p.agg(['mean','median','max','min'])

            Rank         Year      Points
mean    2.483333  2015.033333  771.283333
median  2.500000  2015.000000  762.250000
max     4.000000  2015.666667  812.000000
min     1.666667  2014.500000  752.500000

In [27]:
print(df.groupby('Rank')['Team'].count())

Rank
1    4
2    4
3    2
4    2
Name: Team, dtype: int64

In [30]:
df.groupby('Team')['Rank'].count()

Team
Devils    2
Kings     3
Riders    4
Royals    2
kings     1
Name: Rank, dtype: int64

In [31]:
df.groupby('Team')['Points'].sum()

Team
Devils    1536
Kings     2285
Riders    3049
Royals    1505
kings      812
Name: Points, dtype: int64

In [38]:
df.groupby('Team', as_index=False).agg({"Points": "sum"})

     Team  Points
0  Devils    1536
1   Kings    2285
2  Riders    3049
3  Royals    1505
4   kings     812

In [40]:
df.groupby('Team').Points.mean()

Team
Devils    768.000000
Kings     761.666667
Riders    762.250000
Royals    752.500000
kings     812.000000
Name: Points, dtype: float64

In [42]:
df.groupby('Team').Points.max()

Team
Devils    863
Kings     788
Riders    876
Royals    804
kings     812
Name: Points, dtype: int64

In [43]:
df.groupby('Team').Points.min()

Team
Devils    673
Kings     741
Riders    690
Royals    701
kings     812
Name: Points, dtype: int64

In [45]:
df.groupby('Team').Points.agg(['count','min','max','mean'])

        count  min  max        mean
Team
Devils      2  673  863  768.000000
Kings       3  741  788  761.666667
Riders      4  690  876  762.250000
Royals      2  701  804  752.500000
kings       1  812  812  812.000000

In [49]:
df.groupby('Team').Points.sum()

Team
Devils    1536
Kings     2285
Riders    3049
Royals    1505
kings      812
Name: Points, dtype: int64

In [52]:
df.groupby('Points').agg(['mean','max','min'])

       Rank          Year
       mean max min  mean   max   min
Points
673       3   3   3  2015  2015  2015
690       2   2   2  2017  2017  2017
694       2   2   2  2016  2016  2016
701       4   4   4  2014  2014  2014
741       3   3   3  2014  2014  2014
756       1   1   1  2016  2016  2016
788       1   1   1  2017  2017  2017
789       2   2   2  2015  2015  2015
804       1   1   1  2015  2015  2015
812       4   4   4  2015  2015  2015
863       2   2   2  2014  2014  2014
876       1   1   1  2014  2014  2014

In [61]:
df.groupby('Rank')['Points'].count()

Rank
1    4
2    4
3    2
4    2
Name: Points, dtype: int64

In [65]:
df.groupby('Team')[['Points','Rank']].sum()

        Points  Rank
Team
Devils    1536     5
Kings     2285     5
Riders    3049     7
Royals    1505     5
kings      812     4

**Excersice**

1. Read dataset cars_data.csv
2. Print the columns names of the dataset
3. Print no. of columns and rows in this dataset
4. Find out if there are any NULL or blank values?
5. Find out which column has how many NULL values
6. Change the names of column horsepower to hp
7. Which is the most expensive car?
8. Using slicing create data frame of only Toyota Cars
9. Print count of total cars per company
10. Find each company’s highest price?
11. Find each company’s lowest price?
12. Find average mileage of each car company?

1.Read dataset cars_data.csv

In [2]:
#Read dataset cars_data.csv
df=pd.read_csv('Cars_data.csv')
df

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

2.Print the columns names of the dataset

In [ ]:
#Print the columns names of the dataset
for x in df.columns:
    print(x)

In [5]:
#Print no. of columns and rows in this dataset
print(df.shape)
print("No. of rows:",len(df))
print("No. of columns:",len(df.columns))

(61, 10)
No. of rows: 61
No. of columns: 10

In [94]:
#Find out if there are any NULL or blank values?
print(df.isnull())
print(df.isnull().values.any())  #retutrns TRUE if there are any null values

    index  company  body-style  wheel-base  length  engine-type  \
0   False    False       False       False   False        False
1   False    False       False       False   False        False
2   False    False       False       False   False        False
3   False    False       False       False   False        False
4   False    False       False       False   False        False
..    ...      ...         ...         ...     ...          ...
56  False    False       False       False   False        False
57  False    False       False       False   False        False
58  False    False       False       False   False        False
59  False    False       False       False   False        False
60  False    False       False       False   False        False

    num-of-cylinders  horsepower  average-mileage  price
0              False       False            False  False
1              False       False            False  False
2              False       False            False  False
3              False       False            False  False
4              False       False            False  False
..               ...         ...              ...    ...
56             False       False            False  False
57             False       False            False  False
58             False       False            False  False
59             False       False            False  False
60             False       False            False  False

[61 rows x 10 columns]
True

In [76]:
#Find out which column has how many NULL values
print(df.isnull().sum())

index               0
company             0
body-style          0
wheel-base          0
length              0
engine-type         0
num-of-cylinders    0
horsepower          0
average-mileage     0
price               3
dtype: int64

In [80]:
#Change the names of column horsepower to hp
df.rename(columns={"horsepower":"hp"})

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,hp,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [86]:
#Which is the most expensive car
# print(df['company'][df['price'].max()])
e=pd.DataFrame(df[['company','price']][df.price==df['price'].max()])
e

          company    price
35  mercedes-benz  45400.0

In [91]:
#Using slicing create data frame of only Toyota Cars
df_t=(df[49:55])
df_t.reset_index(inplace = True)
df_t

,level_0,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,49,67,toyota,hatchback,95.7,158.7,ohc,four,62,31,6338.0
1,50,68,toyota,hatchback,95.7,158.7,ohc,four,62,31,6488.0
2,51,69,toyota,wagon,95.7,169.7,ohc,four,62,31,6918.0
3,52,70,toyota,wagon,95.7,169.7,ohc,four,62,27,7898.0
4,53,71,toyota,wagon,95.7,169.7,ohc,four,62,27,8778.0
5,54,79,toyota,wagon,104.5,187.8,dohc,six,156,19,15750.0

In [12]:
#Print count of total cars per company
cars=df.groupby('company').company.count()
print(cars)

company
alfa-romero      3
audi             4
bmw              6
chevrolet        3
dodge            2
honda            3
isuzu            3
jaguar           3
mazda            5
mercedes-benz    4
mitsubishi       4
nissan           5
porsche          3
toyota           7
volkswagen       4
volvo            2
Name: company, dtype: int64

In [36]:
#Find each company’s highest price
print(df.groupby('company')['price'].max())
#print(df.groupby(['company','price']).max())

company
alfa-romero      16500.0
audi             18920.0
bmw              41315.0
chevrolet         6575.0
dodge             6377.0
honda            12945.0
isuzu             6785.0
jaguar           36000.0
mazda            18344.0
mercedes-benz    45400.0
mitsubishi        8189.0
nissan           13499.0
porsche          37028.0
toyota           15750.0
volkswagen        9995.0
volvo            13415.0
Name: price, dtype: float64

In [37]:
#Find each company’s lowest price
print(df.groupby('company')['price'].min())

company
alfa-romero      13495.0
audi             13950.0
bmw              16430.0
chevrolet         5151.0
dodge             6229.0
honda             7295.0
isuzu             6785.0
jaguar           32250.0
mazda             5195.0
mercedes-benz    25552.0
mitsubishi        5389.0
nissan            6649.0
porsche          34028.0
toyota            5348.0
volkswagen        7775.0
volvo            12940.0
Name: price, dtype: float64

In [78]:
#Find average mileage of each car company
m=df.groupby('company')
df_m=m['average-mileage'].mean()
df_m
#print(m['average-mileage'])
#av=df.groupby('company')[['company','average-mileage']]
#print(df.groupby(['company','average-mileage']))

company
alfa-romero      20.333333
audi             20.000000
bmw              19.000000
chevrolet        41.000000
dodge            31.000000
honda            26.333333
isuzu            33.333333
jaguar           14.333333
mazda            28.000000
mercedes-benz    18.000000
mitsubishi       29.500000
nissan           31.400000
porsche          17.000000
toyota           28.714286
volkswagen       31.750000
volvo            23.000000
Name: average-mileage, dtype: float64

In [95]:
#reading excel file
df_iris=pd.read_excel('iris.xlsx')
df_iris

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [96]:
df_iris.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [98]:
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal.Length  150 non-null    float64
 1   Sepal.Width   150 non-null    float64
 2   Petal.Length  150 non-null    float64
 3   Petal.Width   150 non-null    float64
 4   Species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [104]:
#unique values in the column
print(df_iris.Species.unique())

['setosa' 'versicolor' 'virginica']

In [105]:
group=df_iris.groupby('Species')
print(group.get_group('versicolor'))

    Sepal.Length  Sepal.Width  Petal.Length  Petal.Width     Species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor
55           5.7          2.8           4.5          1.3  versicolor
56           6.3          3.3           4.7          1.6  versicolor
57           4.9          2.4           3.3          1.0  versicolor
58           6.6          2.9           4.6          1.3  versicolor
59           5.2          2.7           3.9          1.4  versicolor
60           5.0          2.0           3.5          1.0  versicolor
61           5.9          3.0           4.2          1.5  versicolor
62           6.0          2.2           4.0          1.0  versicolor
63           6.1          2.9           4.7          1.4  versicolor
64           5.6          2.9           3.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor
66           5.6          3.0           4.5          1.5  versicolor
67           5.8          2.7           4.1          1.0  versicolor
68           6.2          2.2           4.5          1.5  versicolor
69           5.6          2.5           3.9          1.1  versicolor
70           5.9          3.2           4.8          1.8  versicolor
71           6.1          2.8           4.0          1.3  versicolor
72           6.3          2.5           4.9          1.5  versicolor
73           6.1          2.8           4.7          1.2  versicolor
74           6.4          2.9           4.3          1.3  versicolor
75           6.6          3.0           4.4          1.4  versicolor
76           6.8          2.8           4.8          1.4  versicolor
77           6.7          3.0           5.0          1.7  versicolor
78           6.0          2.9           4.5          1.5  versicolor
79           5.7          2.6           3.5          1.0  versicolor
80           5.5          2.4           3.8          1.1  versicolor
81           5.5          2.4           3.7          1.0  versicolor
82           5.8          2.7           3.9          1.2  versicolor
83           6.0          2.7           5.1          1.6  versicolor
84           5.4          3.0           4.5          1.5  versicolor
85           6.0          3.4           4.5          1.6  versicolor
86           6.7          3.1           4.7          1.5  versicolor
87           6.3          2.3           4.4          1.3  versicolor
88           5.6          3.0           4.1          1.3  versicolor
89           5.5          2.5           4.0          1.3  versicolor
90           5.5          2.6           4.4          1.2  versicolor
91           6.1          3.0           4.6          1.4  versicolor
92           5.8          2.6           4.0          1.2  versicolor
93           5.0          2.3           3.3          1.0  versicolor
94           5.6          2.7           4.2          1.3  versicolor
95           5.7          3.0           4.2          1.2  versicolor
96           5.7          2.9           4.2          1.3  versicolor
97           6.2          2.9           4.3          1.3  versicolor
98           5.1          2.5           3.0          1.1  versicolor
99           5.7          2.8           4.1          1.3  versicolor

In [109]:
df_iris['Species'].value_counts()

versicolor    50
setosa        50
virginica     50
Name: Species, dtype: int64

In [123]:
mn=df_iris.groupby('Species')['Sepal.Length'].mean()

In [124]:
mn

Species
setosa        5.006
versicolor    5.936
virginica     6.588
Name: Sepal.Length, dtype: float64

In [129]:
df_iris[['Sepal.Length' ,'Sepal.Width' ,'Petal.Length' , 'Petal.Width']].groupby('Sepal.Width').agg(['mean','min','max'])

            Sepal.Length           Petal.Length           Petal.Width       \
                    mean  min  max         mean  min  max        mean  min
Sepal.Width
2.0             5.000000  5.0  5.0     3.500000  3.5  3.5    1.000000  1.0
2.2             6.066667  6.0  6.2     4.500000  4.0  5.0    1.333333  1.0
2.3             5.325000  4.5  6.3     3.250000  1.3  4.4    0.975000  0.3
2.4             5.300000  4.9  5.5     3.600000  3.3  3.8    1.033333  1.0
2.5             5.762500  4.9  6.7     4.512500  3.0  5.8    1.550000  1.1
2.6             6.160000  5.5  7.7     4.880000  3.5  6.9    1.420000  1.0
2.7             5.855556  5.2  6.4     4.622222  3.9  5.3    1.555556  1.0
2.8             6.335714  5.6  7.7     5.042857  4.0  6.7    1.707143  1.2
2.9             6.060000  4.4  7.3     4.350000  1.4  6.3    1.320000  0.2
3.0             6.015385  4.3  7.7     4.234615  1.1  6.6    1.403846  0.1
3.1             6.036364  4.6  6.9     3.790909  1.5  5.6    1.245455  0.1
3.2             5.884615  4.4  7.2     3.753846  1.2  6.0    1.261538  0.2
3.3             6.016667  5.0  6.7     4.200000  1.4  6.0    1.566667  0.2
3.4             5.316667  4.6  6.3     2.466667  1.4  5.6    0.716667  0.2
3.5             5.150000  5.0  5.5     1.416667  1.3  1.6    0.300000  0.2
3.6             5.425000  4.6  7.2     2.475000  1.0  6.1    0.750000  0.1
3.7             5.266667  5.1  5.4     1.500000  1.5  1.5    0.266667  0.2
3.8             6.100000  5.1  7.9     3.300000  1.5  6.7    0.900000  0.2
3.9             5.400000  5.4  5.4     1.500000  1.3  1.7    0.400000  0.4
4.0             5.800000  5.8  5.8     1.200000  1.2  1.2    0.200000  0.2
4.1             5.200000  5.2  5.2     1.500000  1.5  1.5    0.100000  0.1
4.2             5.500000  5.5  5.5     1.400000  1.4  1.4    0.200000  0.2
4.4             5.700000  5.7  5.7     1.500000  1.5  1.5    0.400000  0.4


             max
Sepal.Width
2.0          1.0
2.2          1.5
2.3          1.3
2.4          1.1
2.5          2.0
2.6          2.3
2.7          1.9
2.8          2.4
2.9          1.8
3.0          2.3
3.1          2.4
3.2          2.3
3.3          2.5
3.4          2.4
3.5          0.6
3.6          2.5
3.7          0.4
3.8          2.2
3.9          0.4
4.0          0.2
4.1          0.1
4.2          0.2
4.4          0.4

In [133]:
df=pd.read_csv("https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv")
df

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [151]:
import pandas as pd
import io
import requests
url="https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
s=requests.get(url).content
c=pd.read_csv(io.StringIO(s.decode('utf-8')))
c

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [4]:
url="https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data"
df=pd.read_csv(url)
df.head()

   M  0.455  0.365  0.095   0.514  0.2245   0.101   0.15  15
0  M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.070   7
1  F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.210   9
2  M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.155  10
3  I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.055   7
4  I  0.425  0.300  0.095  0.3515  0.1410  0.0775  0.120   8

In [9]:
d=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00292/Wholesale%20customers%20data.csv")
d.head(10)

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen
0,2,3,12669,9656,7561,214,2674,1338
1,2,3,7057,9810,9568,1762,3293,1776
2,2,3,6353,8808,7684,2405,3516,7844
3,1,3,13265,1196,4221,6404,507,1788
4,2,3,22615,5410,7198,3915,1777,5185
5,2,3,9413,8259,5126,666,1795,1451
6,2,3,12126,3199,6975,480,3140,545
7,2,3,7579,4956,9426,1669,3321,2566
8,1,3,5963,3648,6192,425,1716,750
9,2,3,6006,11093,18881,1159,7425,2098

In [10]:
d['Grocery'].mean()

7951.277272727273

In [14]:
d.groupby('Region').agg(['max','min','mean'])

       Channel                 Fresh                     Milk       \
           max min      mean     max min          mean    max  min
Region
1            2   1  1.233766   56083  18  11101.727273  28326  258
2            2   1  1.404255   32717   3   9887.680851  25071  333
3            2   1  1.332278  112151   3  12533.471519  73498   55

                    Grocery  ...              Frozen                    \
               mean     max  ...         mean    max  min         mean
Region                       ...
1       5486.415584   39694  ...  7403.077922  18711   61  3000.337662
2       5088.170213   67298  ...  9218.595745  60869  131  4045.361702
3       5977.085443   92780  ...  7896.363924  36534   25  2944.594937

       Detergents_Paper                  Delicassen
                    max min         mean        max min         mean
Region
1                 19410   5  2651.116883       6854   7  1354.896104
2                 38102  15  3687.468085       5609  51  1159.702128
3                 40827   3  2817.753165      47943   3  1620.601266

[3 rows x 21 columns]

In [15]:
d.Detergents_Paper.sum()

1267857

In [22]:
d.groupby(['Channel','Region']).get_group((2,3))

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen
0,2,3,12669,9656,7561,214,2674,1338
1,2,3,7057,9810,9568,1762,3293,1776
2,2,3,6353,8808,7684,2405,3516,7844
4,2,3,22615,5410,7198,3915,1777,5185
5,2,3,9413,8259,5126,666,1795,1451
...,...,...,...,...,...,...,...,...
418,2,3,660,8494,18622,133,6740,776
421,2,3,17063,4847,9053,1031,3415,1784
423,2,3,17565,3686,4657,1059,1803,668
424,2,3,16980,2884,12232,874,3213,249
437,2,3,14531,15488,30243,437,14841,1867

In [23]:
d.groupby(['Channel','Region']).Frozen.agg('mean')

Channel  Region
1        1         3127.322034
         2         5745.035714
         3         3656.900474
2        1         2584.111111
         2         1540.578947
         3         1513.200000
Name: Frozen, dtype: float64